# Generated by Django 5.1 on 2024-09-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('student', '0004_rename_adress_studentmodel_address'),
        ('teacher', '0004_rename_adress_teachermodel_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdressModel',
            new_name='AddressModel',
        ),
    ]
