from . import absence_serializers
from . import address_serializers
from . import appsetting_serializers
from . import role_serializers
from . import school_serializers
from . import student_cards_serializers
from . import student_serializers
from . import teacher_serializers
from . import user_serializers
